application: vanbellenet
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /javascripts
  static_dir: javascripts

- url: /pictures
  static_dir: pictures

- url: /.*
  script: helloworld.py
